
## Generate DVI from TeX string

xdvirSignature <- "Generated by xdvir"

typeset <- function(x,
                    engine,
                    tinytex=FALSE,
                    ...) {
    UseMethod("typeset")
}

latex <- function(file, dir, engine, tinytex, sig=TRUE) {
    if (sig) {
        options <- paste0(engine$options,
                          " --output-comment='",
                          xdvirSignature, "'",
                          " --output-directory=",
                          dir)
    } else {
        options <- paste0(engine$options,
                          " --output-directory=",
                          dir)
    }
    if (tinytex) {
        ## Have to run TWICE, once to generate .pdf (that we do not need)
        ## and once to generate .dvi (that will only work if .pdf exists).
        ## Have to only try() because tinytex::latexmk() will only
        ## produce .dvi without error if engine="latex" (hard coded)
        ## (it will still generate .dvi with other engines, it will
        ##  just error out)
        tinytex::latexmk(file,
                         engine=engine$command)
        try(tinytex::latexmk(file,
                             engine=engine$command,
                             engine_args=options),
            silent=TRUE)
    } else {
        system(paste0(engine$command, options))
    }
}

## 'x' is a "TeXdocument" from author()
typeset.TeXdocument <- function(x,
                                engine,
                                tinytex=FALSE,
                                texFile=NULL,
                                ...) {
    if (is.null(texFile)) {
        texFile <- tempfile(fileext=".tex")
    }
    texDir <- dirname(texFile)
    dviFile <- paste0(gsub("[.]tex", "", texFile), engine$dviSuffix)
    writeLines(x, engine, texFile, texDir)
    latex(texFile, texDir, engine, tinytex)
    invisible(dviFile)    
}

## 'x' is the name of a "TeXfile" from author()
typeset.TeXfile <- function(x,
                            engine,
                            tinytex=FALSE,
                            ...) {
    texDir <- dirname(x)
    ## TeX file may not have .tex suffix
    dviFile <- paste0(gsub("[.]tex", "", texFile), engine$dviSuffix)
    latex(x, texDir, engine, tinytex)
    invisible(dviFile)
}
                    
## 'x' is the name of any file containing a TeX document
typeset.character <- function(x,
                              engine,
                              tinytex=FALSE,
                              ...) {
    texDir <- dirname(x)
    ## TeX file may not have .tex suffix
    dviFile <- paste0(gsub("[.]tex", "", x), engine$dviSuffix)
    latex(x, texDir, engine, tinytex, sig=FALSE)
    invisible(dviFile)
}
                    

